# Books Recommendation based on 'Ratings'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read Data into dataframe

In [2]:
books = pd.read_csv("C:\\Users\\Swathi\\Desktop\\Excelr Classes\\Assignments\\9.Recommendation system\\Book.csv",sep=',',encoding= 'unicode_escape')
books.head()

"","User.ID","Book.Title","Book.Rating"
0                 "1",276726,"Classical Mythology",5
1                        "2",276729,"Clara Callan",3
2                "3",276729,"Decision in Normandy",6
3  "4",276736,"Flu: The Story of the Great Influe...
4              "5",276737,"The Mummies of Urumchi",6

# Clean & Tabularize data

In [3]:
# change column name to 'Details' instead of "","User.ID","Book.Title","Book.Rating"
books= books.rename(columns={ books.columns[0]: "Details"})

In [4]:
# Split data in 'Deatils' into seperate columns
book_new = books.Details.str.split('",',expand=True)
book_new.head()

0                                                  1  2
0  "1                        276726,"Classical Mythology  5
1  "2                               276729,"Clara Callan  3
2  "3                       276729,"Decision in Normandy  6
3  "4  276736,"Flu: The Story of the Great Influenza ...  8
4  "5                     276737,"The Mummies of Urumchi  6

In [5]:
#Drop 1st column as its just represents index number/row n
book_new.drop(book_new.columns[[0]], axis=1, inplace=True)
# book_new.head()

In [6]:
# Assign temporary name for columns
book_new.columns = ["Book_Title","Book_Rating"]
# book_new.head()

In [7]:
#split 'Book_Title' columns for seperating "User_ID" &"Book_Title" and store it with dummy dataframe
book_dummy=book_new.Book_Title.str.split(',"',expand=True)
# book_dummy.head()

In [8]:
#concat original dataframe and dummy dataframe
book = pd.concat([book_new, book_dummy], axis =1)
book.head()

Book_Title Book_Rating       0  \
0                        276726,"Classical Mythology           5  276726   
1                               276729,"Clara Callan           3  276729   
2                       276729,"Decision in Normandy           6  276729   
3  276736,"Flu: The Story of the Great Influenza ...           8  276736   
4                     276737,"The Mummies of Urumchi           6  276737   

                                                   1  
0                                Classical Mythology  
1                                       Clara Callan  
2                               Decision in Normandy  
3  Flu: The Story of the Great Influenza Pandemic...  
4                             The Mummies of Urumchi

In [9]:
# drop the 1st column as the data is already split and concated through dummy dataframe
book.drop(book.columns[[0]], axis=1, inplace=True)
book

Book_Rating       0                                                  1
0              5  276726                                Classical Mythology
1              3  276729                                       Clara Callan
2              6  276729                               Decision in Normandy
3              8  276736  Flu: The Story of the Great Influenza Pandemic...
4              6  276737                             The Mummies of Urumchi
...          ...     ...                                                ...
9995           7  162121       American Fried: Adventures of a Happy Eater.
9996           9  162121                              Cannibal In Manhattan
9997           7  162121                    How to Flirt: A Practical Guide
9998           8  162121                                           Twilight
9999           6  162129                       Kids Say the Darndest Things

[10000 rows x 3 columns]

In [10]:
#Assign new column names for the dataframe
book.columns = ["BookRating","UserID","BookTitle"]
book.head()

BookRating  UserID                                          BookTitle
0          5  276726                                Classical Mythology
1          3  276729                                       Clara Callan
2          6  276729                               Decision in Normandy
3          8  276736  Flu: The Story of the Great Influenza Pandemic...
4          6  276737                             The Mummies of Urumchi

In [11]:
#Tablurize and store the cleaned data for better analysis 
book.to_csv("tabluarized_data.csv")

In [12]:
print("Number of rows: ", len(book))
print("Number of columns: ",len(book.columns))
print("Number of rows and columns: ",book.shape)
print("Number of elements: ",book.size)
# print("Number of rows, columns, etc: ", book.info())
# print ("\nIdentify outliers & other info like Mean,median,max,min etc:\n\n",book.describe())

Number of rows:  10000
Number of columns:  3
Number of rows and columns:  (10000, 3)
Number of elements:  30000


In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words = 'english')

In [14]:
book.columns.isnull()
book["BookTitle"].isnull()
book["BookTitle"] = book["BookTitle"].fillna(" ")

In [15]:
# using below code we convert data into vectoriztion

tfidf_matrix = tfidf.fit_transform(book.BookTitle)
print("Shape of Original DF : ",book.shape)
print("Shape of TFIDF Matrix: ",tfidf_matrix.shape)

Shape of Original DF :  (10000, 3)
Shape of TFIDF Matrix:  (10000, 11393)


In [16]:
# This is item to item recoomendation which happens offline

from sklearn.metrics.pairwise import linear_kernel
cosine_sim_matrix = linear_kernel(tfidf_matrix,tfidf_matrix) # cos_sim_matrix is obtained by matrix * matrix
print(cosine_sim_matrix)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [17]:
book['BookTitle']= book['BookTitle'].str.lower()
book.BookTitle.value_counts()

fahrenheit 451                                     5
stardust                                           5
ender's game (ender wiggins saga (paperback))      4
the amber spyglass (his dark materials, book 3)    4
charlie and the chocolate factory                  4
                                                  ..
susie, sadly, and the black torpedo of doom        1
tangle box                                         1
christmas : a holiday treasury                     1
the art of mending : a novel (berg, elizabeth)     1
crimes of neglect                                  1
Name: BookTitle, Length: 9638, dtype: int64

In [18]:
book.drop_duplicates(subset ="BookTitle",keep='first',inplace = True)
book.reset_index(drop=True,inplace = True)

In [19]:
book_index = pd.Series(book.index, index = book['BookTitle'])
book_index.sort_values(ascending=True, inplace=True)
print(book_index)

BookTitle
classical mythology                                                                                      0
clara callan                                                                                             1
decision in normandy                                                                                     2
flu: the story of the great influenza pandemic of 1918 and the search for the virus that caused it       3
the mummies of urumchi                                                                                   4
                                                                                                      ... 
american fried: adventures of a happy eater.                                                          9633
cannibal in manhattan                                                                                 9634
how to flirt: a practical guide                                                                       9635
twilight                   

# create a function for recommending movies

Input = Rating

Output = Top N Recommended of Books 

In [52]:
def get_book_recommendations(BookName,topN):
   
    #1:get Book index(id) using its title bcz user will enter movie name not index number
    book_id = book_index[BookName] 
    #print(book_id)
    
    #2: getting the pair wise similarity score of all the movies with that of enterted movie; here enumerate act as counter
    cosine_scores = list(enumerate(cosine_sim_matrix[book_id])) 
    #print(cosine_scores)
    
    #3: Sorted the obtained score; sort lamda x:x[1] means in dictionary x = [12293(x[0]movie id),0.0(x[1]cosine score)],we shall sort on cosine score
    cosine_scores = sorted(cosine_scores, key=lambda x:x[1], reverse = True)
    #print(cosine_scores)
    
    #4: slice the sorted list as per user input (topN); it can top5,top10 or anything
    cosine_score_TopN = cosine_scores[0:topN]
    print(cosine_score_TopN)

    #5:above will give only index number not the movie name. but customer requires movie name
    # Getting movie index from the top 10 sorted list X[0]= Movie id and X[1] is similarity score
    book_idx = [i[0] for i in cosine_score_TopN]
    book_scores = [i[1] for i in cosine_score_TopN]
    
    #6. Create dataframe to store the similar movie list
    book_similar_show = pd.DataFrame(columns=["BookTitle","Score"])
    
    
    #7. Put the topN data into dataframe
    book_similar_show["BookTitle"] = book.loc[book_idx,"BookTitle"] # using anime index we fetch movie name from anime
    book_similar_show["Score"]= book_scores
    
# #     print("Before Reset:",book_similar_show)
    book_similar_show.reset_index(inplace=True) # this will show anime_idx value as seperate columns
#     print("After Reset:",book_similar_show)
    book_similar_show.drop(["index"],axis=1,inplace=True)
    
    #8.OutPut
    return book_similar_show

In [53]:
Top_N_Books = get_book_recommendations(3,5)
Top_N_Books

[(3, 1.0000000000000002), (7760, 0.23030946840620475), (1341, 0.21897028740099653), (7552, 0.2046583436772717), (2376, 0.16639108548710613)]


BookTitle     Score
0  flu: the story of the great influenza pandemic...  1.000000
1                         el respeto hacia uno mismo  0.230309
2                                   men and brethren  0.218970
3  the golfer's book of wisdom: common sense and ...  0.204658
4                             death of a river guide  0.166391